## Student Performance Prediction

##### Importing libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

##### Read data

In [3]:
df=pd.read_csv('Student_performance_new.csv')

In [4]:
df.head()

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          0                  2        19.833723   
1       1002   18       0          0                  1        15.408756   
2       1003   15       0          2                  3         4.210570   
3       1004   17       1          0                  3        10.028829   
4       1005   17       1          0                  2         4.672495   

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0         7         1                2                0       0      1   
1         0         0                1                0       0      0   
2        26         0                2                0       0      0   
3        14         0                3                1       0      0   
4        17         1                3                0       0      0   

   Volunteering       GPA  GradeClass  
0             0  2.929196         1.0  
1             0  3.042915         1.0  
2             0  0.112602         0.0  
3             0  2.054218         1.0  
4             0  1.288061         0.0

In [5]:
df.shape

(2392, 15)

In [6]:
df.nunique()

StudentID            2392
Age                     4
Gender                  2
Ethnicity               4
ParentalEducation       5
StudyTimeWeekly      2392
Absences               30
Tutoring                2
ParentalSupport         5
Extracurricular         2
Sports                  2
Music                   2
Volunteering            2
GPA                  2371
GradeClass              2
dtype: int64

In [7]:
df.isna().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [8]:
x=df[['StudyTimeWeekly','Absences','GPA']]
x

StudyTimeWeekly  Absences       GPA
0           19.833723         7  2.929196
1           15.408756         0  3.042915
2            4.210570        26  0.112602
3           10.028829        14  2.054218
4            4.672495        17  1.288061
...               ...       ...       ...
2387        10.680555         2  3.455509
2388         7.583217         4  3.279150
2389         6.805500        20  1.142333
2390        12.416653        17  1.803297
2391        17.819907        13  2.140014

[2392 rows x 3 columns]

In [9]:
y=df.GradeClass
y

0       1.0
1       1.0
2       0.0
3       1.0
4       0.0
       ... 
2387    1.0
2388    0.0
2389    1.0
2390    1.0
2391    1.0
Name: GradeClass, Length: 2392, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(df[['StudyTimeWeekly','Absences','GPA']],df.GradeClass,train_size=0.8,random_state=42)

In [12]:
x_train

StudyTimeWeekly  Absences       GPA
642         18.118879        24  1.396278
1752         2.469271        19  0.754751
1401         3.456401        25  0.136166
2032        15.838131        25  1.172192
990          1.045373        19  1.747356
...               ...       ...       ...
1638        13.092424        13  1.595627
1095         2.159249        19  1.523945
1130         3.572578        14  2.051919
1294         4.402585        20  1.348997
860          5.427628        27  0.012063

[1913 rows x 3 columns]

In [13]:
x_test

StudyTimeWeekly  Absences       GPA
1004         0.135763        17  1.427724
196          1.989925         0  3.117354
2342        10.588715        15  2.037769
1708        16.208658         1  3.548521
435          3.576821        27  0.248977
...               ...       ...       ...
986          8.412605        16  1.562360
120          3.170405        12  2.174903
283          5.141922         5  2.332540
1740        10.281614        10  2.777967
1726        15.610436        26  0.863545

[479 rows x 3 columns]

In [14]:
y_train

642     0.0
1752    0.0
1401    0.0
2032    0.0
990     0.0
       ... 
1638    0.0
1095    0.0
1130    1.0
1294    0.0
860     0.0
Name: GradeClass, Length: 1913, dtype: float64

In [15]:
y_test

1004    0.0
196     1.0
2342    1.0
1708    1.0
435     0.0
       ... 
986     0.0
120     1.0
283     1.0
1740    1.0
1726    0.0
Name: GradeClass, Length: 479, dtype: float64

In [16]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [17]:
model.fit(x_train, y_train)

LogisticRegression()

In [18]:
y_predicted = model.predict(x_test)
y_predicted

array([0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1.,
       0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1.,
       1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
       1., 1., 0., 1., 0.

In [19]:
model.score(x_train,y_train)

0.9346576058546785

In [20]:
model.score(x_test,y_test)

0.9352818371607515

In [21]:
model.predict_proba(x_test)

array([[8.66948276e-01, 1.33051724e-01],
       [8.16038900e-03, 9.91839611e-01],
       [4.18448865e-01, 5.81551135e-01],
       [1.93306905e-03, 9.98066931e-01],
       [9.98273911e-01, 1.72608854e-03],
       [7.08899061e-02, 9.29110094e-01],
       [5.33754543e-01, 4.66245457e-01],
       [2.63649996e-01, 7.36350004e-01],
       [2.70769825e-01, 7.29230175e-01],
       [9.87408325e-01, 1.25916747e-02],
       [1.46701878e-01, 8.53298122e-01],
       [9.88556503e-01, 1.14434970e-02],
       [1.99572345e-02, 9.80042766e-01],
       [1.33151693e-01, 8.66848307e-01],
       [4.51259628e-02, 9.54874037e-01],
       [9.98251930e-01, 1.74807007e-03],
       [9.68278754e-01, 3.17212464e-02],
       [8.05606045e-01, 1.94393955e-01],
       [3.71199137e-01, 6.28800863e-01],
       [1.70921093e-01, 8.29078907e-01],
       [5.09536969e-01, 4.90463031e-01],
       [8.12516034e-01, 1.87483966e-01],
       [7.05183289e-01, 2.94816711e-01],
       [8.65899139e-03, 9.91341009e-01],
       [6.939060

In [22]:
model.coef_

array([[ 0.00850395, -0.07000147,  3.23663648]])

In [23]:
model.intercept_

array([-5.30639573])

In [24]:
import math
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [25]:
def prediction_function(Study_time,Absences,GPA):
    z = 0.00850395 * Study_time+-0.07000147*Absences+3.23663648*GPA+-5.30639573
    y = sigmoid(z)
    return y

In [26]:
Study_time,Absences,GPA=19.833722807854716,7,2.929195591667681
prediction_function(Study_time,Absences,GPA) #1 row=0

0.9792247797689925

##### 0.9792247797689925 is greater than 0.5 hence,he will get grade 1

In [27]:
Study_time,Absences,GPA=4.21056976881226,26,0.1126022544661815
prediction_function(Study_time,Absences,GPA) #0 row=3

0.0011976747584842371

##### 0.0011976747584842371  is less than 0.5 hence,he will get grade 0

In [28]:
Study_time,Absences,GPA=7.380354648223455,15,1.5051556220362858
prediction_function(Study_time,Absences,GPA) #0 row=25

0.19434604314468926

##### 0.19434604314468926 is less than 0.5 hence,he will get grade 0